@extends('layout.main')
@section('titolo_head')
  prodotti
@endsection
@section('titolo')
  prodotti
@endsection
@section('nav')
  @include('layout.nav')
@endsection
@section('main')
  @include('layout.print_products')
@endsection
